# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: set use DotNet 5.0
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- script: dotnet build --configuration $(buildConfiguration)
  name: dotnet_build
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: Portal.Services/AzW.Web.API

- task: DotNetCoreCLI@2
  name: dotnet_publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(Build.ArtifactStagingDirectory)/api/publish'


- task: PublishBuildArtifacts@1
  name: publish_build_artifact
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)/api/publish'
     ArtifactName: 'drop'
     publishLocation: 'Container'

  
