# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 - dev

stages:
  - stage: Build
    jobs:
      - job: build_Portal_NPM
         
      
        pool:
          vmImage: ubuntu-latest

        variables:
          REACT_APP_ENV: 'beta'

        steps:       

        - task: CredScan@3
        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo "Structure of work folder of this pipeline:"
              tree $(Agent.WorkFolder)\1 /f
              
              echo "Build.ArtifactStagingDirectory:" 
              echo "$(Build.ArtifactStagingDirectory)"
              echo "Build.BinariesDirectory:" 
              echo "$(Build.BinariesDirectory)"
              echo "Build.SourcesDirectory:"
              echo "$(Build.SourcesDirectory)"
              echo "Build.SourcesDirectory:"
              echo "$(Build.SourcesDirectory)"
              echo "Agent.BuildDirectory:"
              echo "$(Agent.BuildDirectory)"

        - task: Bash@3
          env:
            REACT_APP_ENV: '${{ variables.REACT_APP_ENV }}'
          displayName: Npm Install
          inputs:
            targetType: 'inline'
            workingDirectory: 'src/Portal'
            bashEnvValue: 
            script: |
              - script: |
                  echo REACT_APP_ENV=beta
                  npm install
                  npm run build

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(build.sourcesdirectory)/src/Portal/build'
            Contents: '**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'drop'
            

  - stage: Deploy_App_Service
    jobs:
      -  deployment:
         environment: Dev
         condition: 
         strategy:
          runOnce:
              deploy:
                 steps:

                    # - task: AzureAppServiceManage@0
                    #   displayName: Stop portal-azworkbench-dev
                    #   inputs:
                    #     azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                    #     Action: 'Stop Azure App Service'
                    #     WebAppName: 'portal-azworkbench-dev'

                    - task: AzureWebApp@1
                      displayName: Deploy to portal-azworkbench-dev
                      inputs:
                        azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                        appType: 'webApp'
                        appName: 'portal-azworkbench-dev'
                        package: '$(System.ArtifactsDirectory)/drop'
                        deploymentMethod: 'zipDeploy'
                        
                    # - task: AzureAppServiceManage@0
                    #   displayName: Start portal-azworkbench-dev
                    #   inputs:
                    #     azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                    #     Action: 'Start Azure App Service'
                    #     WebAppName: 'portal-azworkbench-dev'


                        
                    
                    
  