
trigger:
 - master

variables:
  - group: Common
  - name: APPROVAL_CHECK
    value: $[variables.APPROVAL_CHECK]
  - name: apiserverSrcDirectory
    value: src/ApiServer/AzW.Web.API
  - name: webappName
    value: webapp-api-prod
 
stages:
    - stage: Build
      jobs:
          - job: Build_ApiServer
      
            pool:
                vmImage: ubuntu-latest
        
            steps:
            
             - task: CredScan@3
               inputs:
                 outputFormat: 'csv'
                 scanFolder: $(apiserverSrcDirectory)

             - task: ComponentGovernanceComponentDetection@0
               inputs:
                 scanType: 'Register'
                 verbosity: 'Verbose'
                 sourceScanPath: '$(apiserverSrcDirectory)'
                 alertWarningLevel: 'High'
            
             - task: UseDotNet@2
               displayName: set sdk .Net 5.0
               inputs:
                 packageType: 'sdk'
                 version: '5.0.x'
                 
             - task: DotNetCoreCLI@2
               displayName: dotnet build
               inputs:
                 command: 'build'
                 workingDirectory: $(apiserverSrcDirectory)
                 
             
             - task: DotNetCoreCLI@2
               displayName: dotnet publish
               inputs:
                  command: 'publish'
                  publishWebProjects: true
                  arguments: '-o $(Build.ArtifactStagingDirectory)/publish'
                  zipAfterPublish: false
                  workingDirectory: $(apiserverSrcDirectory)
                  
             - task: PublishBuildArtifacts@1
               displayName: publish build artifact
               inputs:
                 PathtoPublish: $(Build.ArtifactStagingDirectory)/publish/AzW.Web.API
                 ArtifactName: 'drop'
                 
                 
    - stage: Deploy
      jobs:
        - deployment:
          environment: Dev
          strategy:
            runOnce:
              deploy:
                steps:
                
                 - task: DownloadBuildArtifacts@1
                   displayName: Download artifact
                   inputs:
                      buildType: 'current'
                      downloadType: 'single'
                      artifactName: 'drop'
                      downloadPath: '$(System.DefaultWorkingDirectory)'
                      
                 - task: AzureRmWebAppDeployment@4
                   inputs:
                      ConnectionType: 'AzureRM'
                      azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                      appType: 'webApp'
                      WebAppName: $(webappName)
                      packageForLinux: '$(System.DefaultWorkingDirectory)/drop'

                 
        