# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
    include:
      - dev
    exclude:
      - master
      - release-v1.0.0-24022022
      - release-v1.0.1-10032022

stages:
  - stage: Build
    jobs:
      - job: build_Portal_NPM
         
      
        pool:
          vmImage: ubuntu-latest

        variables:
          REACT_APP_ENV: 'beta'

        steps:        
        #- task: CredScan@3

        - task: Bash@3
          env:
            REACT_APP_ENV: '${{ variables.REACT_APP_ENV }}'
          displayName: Npm Install
          inputs:
            targetType: 'inline'
            workingDirectory: 'src/Portal'
            bashEnvValue: 
            script: |
              - script: |
                  echo REACT_APP_ENV=${{ variables.REACT_APP_ENV }}
                  npm install
                  npm run build

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(build.sourcesdirectory)/src/Portal/build'
            Contents: '**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: drop
            StoreAsTar: true
            

  - stage: Deploy_App_Service
    jobs:
      -  deployment:
         environment: Dev
         strategy:
          runOnce:
              deploy:
                 steps:
                   
                    - task: DownloadBuildArtifacts@0
                      inputs:
                        buildType: 'current'
                        downloadType: 'single'
                        artifactName: 'drop'
                        downloadPath: '$(System.ArtifactsDirectory)'

                    - task: AzureRmWebAppDeployment@4
                      inputs:
                        ConnectionType: 'AzureRM'
                        azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                        appType: 'webApp'
                        WebAppName: 'portal-azworkbench-dev'
                        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
  