# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: set use DotNet 5.0
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- script: |
    echo build in directory Portal.Services/AzW.Web.API

- script: dotnet restore Portal.Services/AzW.Web.API
  name: restore
  displayName: 'dotnet restore'

- script: dotnet build Portal.Services/AzW.Web.API --configuration $(buildConfiguration)
  name: dotnet_build
  displayName: 'dotnet build'

- script: |
    echo publishing Backend.API to directory: $(Build.ArtifactStagingDirectory)/api/publish

- script: dotnet publish Portal.Services/AzW.Web.API -o $(Build.ArtifactStagingDirectory)/api/publish
  name: dotnet_build
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  name: dotnet_publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(Build.ArtifactStagingDirectory)/api/publish'


- task: PublishBuildArtifacts@1
  name: publish_build_artifact
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)/api/publish'
     ArtifactName: 'drop'
     publishLocation: 'Container'

  
