# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  name: dotnet-restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    restoreDirectory: 'Portal.Services/AzW.Web.API'

- script: dotnet build --configuration $(buildConfiguration)
  name: dotnet-build
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: Portal.Services/AzW.Web.API

- task: DotNetCoreCLI@2
  name: dotnet-publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(Build.ArtifactStagingDirectory)/api/publish'


- task: PublishBuildArtifacts@1
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)/api/publish'
     ArtifactName: 'drop'
     publishLocation: 'Container'

  
