# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
    include:
      - dev
    exclude:
      - master
      - release-v1.0.0-24022022
      - release-v1.0.1-10032022

stages:
  - stage: Build
    jobs:
      - job: build_Portal_NPM
         
      
        pool:
          vmImage: ubuntu-latest

        variables:
          REACT_APP_ENV: 'beta'

        steps:        
        
        
        #- task: CredScan@3
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo "Structure of work folder of this pipeline:"
              tree $(Agent.WorkFolder)\1 /f
              
              echo "Build.ArtifactStagingDirectory:" 
              echo "$(Build.ArtifactStagingDirectory)"
              echo "Build.BinariesDirectory:" 
              echo "$(Build.BinariesDirectory)"
              echo "Build.SourcesDirectory:"
              echo "$(Build.SourcesDirectory)"
              echo "Build.SourcesDirectory:"
              echo "$(Build.SourcesDirectory)"
              echo "Agent.BuildDirectory:"
              echo "$(Agent.BuildDirectory)"

        - task: Bash@3
          env:
            REACT_APP_ENV: '${{ variables.REACT_APP_ENV }}'
          displayName: Npm Install
          inputs:
            targetType: 'inline'
            workingDirectory: 'src/Portal'
            bashEnvValue: 
            script: |
              - script: |
                  echo REACT_APP_ENV=${{ variables.REACT_APP_ENV }}
                  npm install
                  npm run build

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(build.sourcesdirectory)/src/Portal/build'
            Contents: '**'
            targetFolder: '$(Build.ArtifactStagingDirectory)/build'
            
        # - task: ArchiveFiles@2
        #   inputs:
        #     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build'
        #     includeRootFolder: true
        #     archiveType: 'zip'
        #     archiveFile: '$(Build.ArtifactStagingDirectory)/build/portal.zip'
        #     replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)/build'
            artifactName: 'drop'
            StoreAsTar: false
            

  - stage: Deploy_App_Service
    jobs:
      -  deployment:
         environment: Dev
         strategy:
          runOnce:
              deploy:
                 steps:
                   
                    # - task: DownloadBuildArtifacts@0
                    #   inputs:
                    #     buildType: 'current'
                    #     downloadType: 'single'
                    #     artifactName: 'drop'
                    #     downloadPath: '$(System.ArtifactsDirectory)'

                    # - task: DownloadBuildArtifacts@1
                    #   displayName: Download artifact drop.tar
                    #   inputs:
                    #     buildType: 'current'
                    #     downloadType: 'single'
                    #     artifactName: 'drop'
                    #     itemPattern: '**/drop.tar'
                    #     downloadPath: '$(Build.ArtifactStagingDirectory)/tar'
                        
                    # - task: ExtractFiles@1
                    #   inputs:
                    #     archiveFilePatterns: '$(System.ArtifactsDirectory)/drop/*.zip'
                    #     destinationFolder: '$(Build.ArtifactsDirectory)/unzip'
                    #     cleanDestinationFolder: true
                    #     overwriteExistingFiles: true

                    - task: AzureWebApp@1
                      inputs:
                        azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
                        appType: 'webApp'
                        appName: 'portal-azworkbench-dev'
                        package: '$(System.ArtifactsDirectory)'
                        deploymentMethod: 'zipDeploy'


                        
                    
                    
  