# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self
  

# variables:
#   - group: Dev
#   - name: major
#     value: $[variables.PYBICEP_DOCKERIMAGE_VERSION_MAJOR]
    
#   # Container registry service connection established during pipeline creation
#   #dockerRegistryServiceConnection: '5585900c-e623-41f3-ab62-dd91d9a9bb66'
#   containerRegistry: 'acrazworkbenchdev.azurecr.io'
#   imageRepository: 'pybicep'
#   appServiceName: 'webapp-pybicep-container-dev'
#   major: $(variables['']) #variables['PYBICEP_DOCKERIMAGE_VERSION_MAJOR'])
#   minor: $[variables.PYBICEP_DOCKERIMAGE_VERSION_MINOR]
#   patch: $[variables.PYBICEP_DOCKERIMAGE_VERSION_PATCH]
#   buildDate: ''
#   tag: pybicep-$(major).$(minor).$(patch).$(buildDate)
#   imageName: $(containerRegistry)/$(imageRepository):$(tag)

variables:
  - group: Dev
  - name: major
    value: $[variables.PYBICEP_DOCKERIMAGE_VERSION_MAJOR]
  - name: minor
    value: $[variables.PYBICEP_DOCKERIMAGE_VERSION_MINOR]
  - name: patch
    value: $[variables.PYBICEP_DOCKERIMAGE_VERSION_PATCH]

  # Container registry service connection established during pipeline creation
  #dockerRegistryServiceConnection: '5585900c-e623-41f3-ab62-dd91d9a9bb66'
  - name: containerRegistry
    value: 'acrazworkbenchdev.azurecr.io'
  - name: imageRepository
    value: 'pybicep'
  - name: appServiceName
    value: 'webapp-pybicep-container-dev'
  - name: buildDate
    value: ''
  - name: tag
    value: pybicep-$(major).$(minor).$(patch).$(buildDate)
  - name: imageName
    value: $(containerRegistry)/$(imageRepository):$(tag)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push PyBicep to $(containerRegistry)
  jobs:
  - job: Build
    displayName: Build
    
    steps:
      - powershell: |
          Set-Variable -Name d -Value (Get-Date).ToString('yyyyMMdd')
          Write-Host "##vso[task.setvariable variable=buildDate]$d"
          
      - task: CmdLine@2
          inputs:
            script: echo $(imageName)
    
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     containerRegistry: 'AcrAzWorkbenchDev'
    #     repository: $(imageRepository)
    #     command: 'buildAndPush'
    #     dockerfile: $(Build.SourcesDirectory)/src/BicepGenerator/Dockerfile
    #     tags: $(tag)


# - stage:
#   displayName: Deploy Pybicep to App Service $(appServiceName)
#   jobs:
#     - deployment: 
#       environment: Dev
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#               - task: AzureWebAppContainer@1
#                 displayName: Deploy PyBicep container to App Service
#                 inputs:
#                   azureSubscription: 'Weixian-Azure(ee611083-4581-4ba1-8116-a502d4539206)'
#                   appName: '$(appServiceName)'
#                   containers: '$(imageName)'