export const MSAL_LOGIN = "MSAL_LOGIN";
export const MSAL_LOGIN_SUCCESS = "MSAL_LOGIN_SUCCESS";
export const MSAL_LOGIN_FAILED = "MSAL_LOGIN_FAILED";
export const MSAL_LOGOUT = "MSAL_LOGOUT";

export const EDITOR_LOAD_SERVICES = "EDITOR_LOAD_SERVICES";