export default class ResourceType
{
    static WindowsVM() {return 'vmWindows'; }
    static LinuxVM() {return 'vmLinux'; }
    static VM() {return 'vm'; }
    static VMSS() {return 'vmss'; }
    static AppService() {return 'appsvc'; }
    static ASE() {return 'ase'; }
    static Function() {return 'func'; }
    static VNet() {return 'vnet'; }
    static Subnet() {return 'subnet'; }
    static NLB() {return 'nlb'; }
    static AppGw() {return 'appgw'; }
    static DNSPrivateZone() {return 'dnsprivatezone'; }
    static AzureSearch() {return 'search'; }
    static SignalR() {return 'signalr'; }
    static AppServiceCert() {return 'appsvccert'; }
    static AppServiceDomain() {return 'appsvcdomain'; }
    static SharedImageGallery() {return 'sig'; }
    static FrontDoor() {return 'frontdoor'; }
    static PublicIp() {return 'pip'; }
    static ExpressRouteCircuit() {return 'expressroute'; }
    static TrafficManager() {return 'trafficmanager'; }
    static DevTestLab() {return 'devtestlab'; }
    static VirtualNetworkGateway() {return 'vnetgateway'; }
    static CDN() {return 'cdn'; }
    static ASG() {return 'asg'; }
    static NIC() {return 'nic'; }
    static BlobStorage() {return 'blobstorage'; }
    static AzFile() {return 'azfile'; }
    static AzFileSync() {return 'azfilesync'; }
    static NetAppFile() {return 'netappfile'; }
    static QueueStorage() {return 'queuestorage'; }
    static TableStorage() {return 'tablestorage'; }
    static Databox() {return 'databox'; }
    static PostgreSQL() {return 'postgresql'; }
    static MariaDB() {return 'maria'; }
    static SQLDB() {return 'sqldb'; }
    static CosmosDB() {return 'cosmos'; }
    static MySQL() {return 'mysql'; }
    static SQLElasticPool() {return 'sqlelasticpool'; }
    static SQLMI() {return 'sqlmi'; }
    static SQLStretchDB() {return 'sqlstretchdb'; }
    static Redis() {return 'redis'; }
    static DataLakeStorage() {return 'datalakestorage'; }
    static Synapse() {return 'synapse'; }
    static DataExplorer() {return 'dataexplorer'; }
    static Databricks() {return 'databricks'; }
    static DataFactory() {return 'datafactory'; }
    static DataLakeAnalytics() {return 'datalakeanalytics'; }
    static HdInsight() {return 'hdinsight'; }
    static ContainerInstance() {return 'containerinstance'; }
    static ContainerRegistry() {return 'containerregistry'; }
    static Kubernetes() {return 'kube'; }

    static APIM() {return 'apim'; }
    static ASB() {return 'asb'; }
    static Relay() {return 'relay'; }
    static LogicApp() {return 'logicapp'; }
    static ISE() {return 'ise'; }
    static EventGridTopic() {return 'egtopic'; }
    static EventGridSubscription() {return 'egsubscription'; }
    static StreamAnalytics() {return 'streamanalytics'; }
    static SendGrid() {return 'sendgrid'; }
    static AppConfig() {return 'appconfig'; }
    static Firewall() {return 'firewall'; }
    static Sentinel() {return 'sentinel'; }
    static KeyVault() {return 'keyvault'; }
    static SecurityCenter() {return 'asc'; }
    static DDoSStandard() {return 'ddosstandard'; }
    static Bastion() {return 'bastion'; }

    static RecoveryServiceVault() {return 'recoveryservicevault'; }
    static AppInsights() {return 'appinsights'; }
    static LogAnalytics() {return 'loganalytics'; }
    static Automation() {return 'automation'; }

    static AAD() {return 'aad'; }
    static AADB2C() {return 'aadb2c'; }
    static IoTHub() {return 'iothub'; }
    static AzureMaps() {return 'maps'; }
    static TimeSeriesInsights() {return 'timeseriesinsights'; }
}